# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Bas Binaries
tagline:          'A Technology Blog'
description:      '"Men have become the tools of their tools." - Henry David Thoreau'
url:              mrb101.github.io

author:
  name:           'Basel J. Hamadeh'
  url:            https://twitter.com/mrb_101

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/mrb101
